export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kama"
ENABLE_CORRECTION="true"
plugins=(git rails ruby brew gem osx docker notify nyan)

source $ZSH/oh-my-zsh.sh

eval $(thefuck --alias)

alias update-all="brew update && brew upgrade && brew cleanup && brew cu -ay && brew cask cleanup && apm update && apm upgrade && softwareupdate -ia"
alias update-dns="sudo killall -HUP mDNSResponder"
alias update-conf="cp /keybase/private/kama/ssh_conf/* ~/.ssh"

alias cat="lolcat"
alias rm="trash"
alias resource="source ~/.zshrc"
alias ip="curl -4 icanhazip.com && curl -6 icanhazip.com"
alias review="merge --no-ff --no-commit"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
alias rs="rails server -b 0.0.0.0"
alias rs-sync="bundle exec rake browser_sync:start"

export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"

PATH=~/.nexustools:$PATH

zstyle ':notify:*' error-icon "https://media3.giphy.com/media/10ECejNtM1GyRy/200_s.gif"
zstyle ':notify:*' error-title "wow such #fail"
zstyle ':notify:*' error-sound "Glass"
zstyle ':notify:*' success-icon "https://s-media-cache-ak0.pinimg.com/564x/b5/5a/18/b55a1805f5650495a74202279036ecd2.jpg"
zstyle ':notify:*' success-title "very #success. wow"
zstyle ':notify:*' success-sound "default"
zstyle ':notify:*' activate-terminal yes
zstyle ':notify:*' command-complete-timeout 15

PATH="$HOME/.fastlane/bin:$PATH"

alias gbb='git merge-base $(current_branch) master'
alias gco='git checkout'
alias ggpull='git pull origin $(current_branch)'
alias ggpush='git push origin $(current_branch)'
alias ggpusht='git push origin $(current_branch) --tags'
alias gl='git log --all --graph -100 --color --decorate --pretty=format:"%C(yellow)%h%Creset %Cred%d%Creset %s %Cblue<%an>%Creset [%ar]"'
alias gfa='git fetch --all -p'
alias gls='git ls-files'
alias gsquash='git rebase -i $(gbb)'
alias gst='git status'
alias current_branch='git symbolic-ref HEAD | awk -F"/" '\''{print $NF}'\'''
alias cub='current_branch'
alias gffs='git stash && git checkout production && git fetch --all --prune && git pull'
